### PR TITLE
Make PNPSSL protocol configurable

### PR DESCRIPTION
**Pull request by fviale**
- encryption protocol is controlled by a property to let users choose between TLSv1.2 (default) and TLSv1.3
 - enable cypher suites needed by TLSv1.3
 - TLSv1.3 is unstable on windows due to a JDK issue, thus we cannot set it as default.

### CODE REVIEW

**Review by medou-boushab — APPROVED** [review]

**Review by mboussaa — APPROVED** [review]

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Comment by fviale** [comment]
Retest this please

**Review by mklkun — APPROVED** [review]

**Pull request merged**
