### PR TITLE
Bump dependencies (step 1)

### PR DESCRIPTION
**Pull request by laurentpellegrino**
Related to ow2-proactive/scheduling#2281

### CODE REVIEW

**Comment by youribonnaffe** [comment]
retest this please

**Comment by lpellegr** [comment]
Retest this please.

**Comment by laurentpellegrino** [comment]
@ow2-proactive/developers Could two people please review the changes?

**Comment by fviale** [comment]
as long as all test pass in various protocols I'm fine with it.

**Comment by laurentpellegrino** [comment]
@fviale It seems that some tests are not passing with the master when started with a specific protocol (cf. https://github.com/ow2-proactive/programming/issues/1304)...

**Comment by lpellegr** [comment]
Retest this please.

**Comment by laurentpellegrino** [comment]
Retest this please.

**Pull request merged**
